//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPrincipal.MeuServicos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MeuServicos.MeuServicoSoap")]
    public interface MeuServicoSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AppPrincipal.MeuServicos.HelloWorldResponse HelloWorld(AppPrincipal.MeuServicos.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AppPrincipal.MeuServicos.HelloWorldResponse> HelloWorldAsync(AppPrincipal.MeuServicos.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Somar", ReplyAction="*")]
        int Somar(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Somar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SomarAsync(int a, int b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AppPrincipal.MeuServicos.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AppPrincipal.MeuServicos.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppPrincipal.MeuServicos.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AppPrincipal.MeuServicos.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MeuServicoSoapChannel : AppPrincipal.MeuServicos.MeuServicoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MeuServicoSoapClient : System.ServiceModel.ClientBase<AppPrincipal.MeuServicos.MeuServicoSoap>, AppPrincipal.MeuServicos.MeuServicoSoap {
        
        public MeuServicoSoapClient() {
        }
        
        public MeuServicoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MeuServicoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeuServicoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeuServicoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppPrincipal.MeuServicos.HelloWorldResponse AppPrincipal.MeuServicos.MeuServicoSoap.HelloWorld(AppPrincipal.MeuServicos.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AppPrincipal.MeuServicos.HelloWorldRequest inValue = new AppPrincipal.MeuServicos.HelloWorldRequest();
            inValue.Body = new AppPrincipal.MeuServicos.HelloWorldRequestBody();
            AppPrincipal.MeuServicos.HelloWorldResponse retVal = ((AppPrincipal.MeuServicos.MeuServicoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppPrincipal.MeuServicos.HelloWorldResponse> AppPrincipal.MeuServicos.MeuServicoSoap.HelloWorldAsync(AppPrincipal.MeuServicos.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppPrincipal.MeuServicos.HelloWorldResponse> HelloWorldAsync() {
            AppPrincipal.MeuServicos.HelloWorldRequest inValue = new AppPrincipal.MeuServicos.HelloWorldRequest();
            inValue.Body = new AppPrincipal.MeuServicos.HelloWorldRequestBody();
            return ((AppPrincipal.MeuServicos.MeuServicoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Somar(int a, int b) {
            return base.Channel.Somar(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SomarAsync(int a, int b) {
            return base.Channel.SomarAsync(a, b);
        }
    }
}
